### ISSUE TITLE
Create TypeScript typings

### ISSUE THREAD

**Issue by jessepinho** [JamieDixon/react-lifecycle-component#12]
Using this component in a TypeScript context means losing all type safety.

I can try my hand at writing typings for this, but I was already trying to while writing my own version of this module (before discovering that this one existed), and it was a struggle.

Are there currently any plans to do this?

(Note to self, in case I take this on: extending the react-redux `connect()` interface and then [excluding](https://stackoverflow.com/questions/44152084/typescript-type-exclusion) the `ComponentLifecycle` interface might work...?)

**Comment by pixelshaded** [comment]
These are mine:
`
declare module 'react-lifecycle-component' {
  import { ComponentLifecycle } from 'react';
  import {
    DispatchProp, InferableComponentEnhancer, InferableComponentEnhancerWithProps, MapDispatchToPropsParam,
    MapStateToPropsParam, MergeProps, Options,
  } from 'react-redux';

  export interface LifecycleStateProps<P = {}> {
    component: React.ComponentType<P>;
  }

  export interface LifecycleDispatchProps<P = {}, S = {}> extends ComponentLifecycle<P, S> {
  }

  export interface Props<P = {}, S = {}> extends LifecycleStateProps<P>, LifecycleDispatchProps<P, S> {}

  export class LifecycleComponent<P = {}, S = {}>
    extends React.Component<P & LifecycleStateProps<P> & LifecycleDispatchProps<P, S>, S> {}

  export function applyLifecycle<P = {}, S = {}>(
    component: React.ComponentType<P>,
  ): React.ComponentType<P & LifecycleDispatchProps<P, S>>;

  export function connectWithLifecycle(): InferableComponentEnhancer<DispatchProp<any>>;

  export function connectWithLifecycle<
    TStateProps,
    no_dispatch,
    TOwnProps,
  >(
    mapStateToProps: MapStateToPropsParam<TStateProps, TOwnProps>,
  ): InferableComponentEnhancerWithProps<TStateProps & DispatchProp<any>, TOwnProps>;

  export function connectWithLifecycle<
    TStateProps,
    TDispatchProps extends LifecycleDispatchProps<any>,
    TOwnProps,
  >(
    mapStateToProps: MapStateToPropsParam<TStateProps, TOwnProps>,
    mapDispatchToProps: MapDispatchToPropsParam<TDispatchProps, TOwnProps>,
  ): InferableComponentEnhancerWithProps<TStateProps & TDispatchProps, TOwnProps>;

  export function connectWithLifecycle<
    TStateProps,
    no_dispatch,
    TOwnProps,
    TMergedProps extends LifecycleDispatchProps<any>,
  >(
    mapStateToProps: MapStateToPropsParam<TStateProps, TOwnProps>,
    mapDispatchToProps: null | undefined,
    mergeProps: MergeProps<TStateProps, undefined, TOwnProps, TMergedProps>,
  ): InferableComponentEnhancerWithProps<TMergedProps, TOwnProps>;

  export function connectWithLifecycle<
    TStateProps,
    TDispatchProps extends LifecycleDispatchProps<any>,
    TOwnProps,
    TMergedProps extends LifecycleDispatchProps<any>,
  >(
    mapStateToProps: MapStateToPropsParam<TStateProps, TOwnProps>,
    mapDispatchToProps: MapDispatchToPropsParam<TDispatchProps, TOwnProps>,
    mergeProps: MergeProps<TStateProps, TDispatchProps, TOwnProps, TMergedProps>,
  ): InferableComponentEnhancerWithProps<TMergedProps, TOwnProps>;

  export function connectWithLifecycle<
    TStateProps,
    no_dispatch,
    TOwnProps,
  >(
    mapStateToProps: MapStateToPropsParam<TStateProps, TOwnProps>,
    mapDispatchToProps: null | undefined,
    mergeProps: null | undefined,
    options: Options<TStateProps, TOwnProps>,
  ): InferableComponentEnhancerWithProps<DispatchProp<any> & TStateProps, TOwnProps>;

  export function connectWithLifecycle<
    TStateProps,
    TDispatchProps extends LifecycleDispatchProps<any>,
    TOwnProps,
  >(
    mapStateToProps: MapStateToPropsParam<TStateProps, TOwnProps>,
    mapDispatchToProps: MapDispatchToPropsParam<TDispatchProps, TOwnProps>,
    mergeProps: null | undefined,
    options: Options<TStateProps, TOwnProps>,
  ): InferableComponentEnhancerWithProps<TStateProps & TDispatchProps, TOwnProps>;

  export function connectWithLifecycle<
    TStateProps,
    TDispatchProps extends LifecycleDispatchProps<any>,
    TOwnProps,
    TMergedProps extends LifecycleDispatchProps<any>,
  >(
    mapStateToProps: MapStateToPropsParam<TStateProps, TOwnProps>,
    mapDispatchToProps: MapDispatchToPropsParam<TDispatchProps, TOwnProps>,
    mergeProps: MergeProps<TStateProps, TDispatchProps, TOwnProps, TMergedProps>,
    options: Options<TStateProps, TOwnProps, TMergedProps>,
  ): InferableComponentEnhancerWithProps<TMergedProps, TOwnProps>;
}
`

**Comment by pixelshaded** [comment]
These are mine:

```typescript
declare module 'react-lifecycle-component' {
  import { ComponentLifecycle } from 'react';
  import {
    DispatchProp, InferableComponentEnhancer, InferableComponentEnhancerWithProps, MapDispatchToPropsParam,
    MapStateToPropsParam, MergeProps, Options,
  } from 'react-redux';

  export interface LifecycleStateProps<P = {}> {
    component: React.ComponentType<P>;
  }

  export interface LifecycleDispatchProps<P = {}, S = {}> extends ComponentLifecycle<P, S> {
  }

  export interface Props<P = {}, S = {}> extends LifecycleStateProps<P>, LifecycleDispatchProps<P, S> {}

  export class LifecycleComponent<P = {}, S = {}>
    extends React.Component<Props<P, S>> {}

  export function applyLifecycle<P = {}, S = {}>(
    component: React.ComponentType<P>,
  ): React.ComponentType<P & LifecycleDispatchProps<P, S>>;

  export function connectWithLifecycle(): InferableComponentEnhancer<DispatchProp<any>>;

  export function connectWithLifecycle<
    TStateProps,
    no_dispatch,
    TOwnProps,
  >(
    mapStateToProps: MapStateToPropsParam<TStateProps, TOwnProps>,
  ): InferableComponentEnhancerWithProps<TStateProps & DispatchProp<any>, TOwnProps>;

  export function connectWithLifecycle<
    TStateProps,
    TDispatchProps extends LifecycleDispatchProps<any>,
    TOwnProps,
  >(
    mapStateToProps: MapStateToPropsParam<TStateProps, TOwnProps>,
    mapDispatchToProps: MapDispatchToPropsParam<TDispatchProps, TOwnProps>,
  ): InferableComponentEnhancerWithProps<TStateProps & TDispatchProps, TOwnProps>;

  export function connectWithLifecycle<
    TStateProps,
    no_dispatch,
    TOwnProps,
    TMergedProps extends LifecycleDispatchProps<any>,
  >(
    mapStateToProps: MapStateToPropsParam<TStateProps, TOwnProps>,
    mapDispatchToProps: null | undefined,
    mergeProps: MergeProps<TStateProps, undefined, TOwnProps, TMergedProps>,
  ): InferableComponentEnhancerWithProps<TMergedProps, TOwnProps>;

  export function connectWithLifecycle<
    TStateProps,
    TDispatchProps extends LifecycleDispatchProps<any>,
    TOwnProps,
    TMergedProps extends LifecycleDispatchProps<any>,
  >(
    mapStateToProps: MapStateToPropsParam<TStateProps, TOwnProps>,
    mapDispatchToProps: MapDispatchToPropsParam<TDispatchProps, TOwnProps>,
    mergeProps: MergeProps<TStateProps, TDispatchProps, TOwnProps, TMergedProps>,
  ): InferableComponentEnhancerWithProps<TMergedProps, TOwnProps>;

  export function connectWithLifecycle<
    TStateProps,
    no_dispatch,
    TOwnProps,
  >(
    mapStateToProps: MapStateToPropsParam<TStateProps, TOwnProps>,
    mapDispatchToProps: null | undefined,
    mergeProps: null | undefined,
    options: Options<TStateProps, TOwnProps>,
  ): InferableComponentEnhancerWithProps<DispatchProp<any> & TStateProps, TOwnProps>;

  export function connectWithLifecycle<
    TStateProps,
    TDispatchProps extends LifecycleDispatchProps<any>,
    TOwnProps,
  >(
    mapStateToProps: MapStateToPropsParam<TStateProps, TOwnProps>,
    mapDispatchToProps: MapDispatchToPropsParam<TDispatchProps, TOwnProps>,
    mergeProps: null | undefined,
    options: Options<TStateProps, TOwnProps>,
  ): InferableComponentEnhancerWithProps<TStateProps & TDispatchProps, TOwnProps>;

  export function connectWithLifecycle<
    TStateProps,
    TDispatchProps extends LifecycleDispatchProps<any>,
    TOwnProps,
    TMergedProps extends LifecycleDispatchProps<any>,
  >(
    mapStateToProps: MapStateToPropsParam<TStateProps, TOwnProps>,
    mapDispatchToProps: MapDispatchToPropsParam<TDispatchProps, TOwnProps>,
    mergeProps: MergeProps<TStateProps, TDispatchProps, TOwnProps, TMergedProps>,
    options: Options<TStateProps, TOwnProps, TMergedProps>,
  ): InferableComponentEnhancerWithProps<TMergedProps, TOwnProps>;
}
```

**Comment by JamieDixon** [comment]
I'm not too familiar with typescript but if the typings provided above by @pixelshaded work as intended, I'd be happy to receive a PR adding them to the project.

Is there a central repository of typings for typescript like there is with flow and flow-typed? Or would we have them in this project?

**Comment by pixelshaded** [comment]
so with typescript you can either include the .d.ts file in the root of your module or add it to @types https://github.com/DefinitelyTyped/DefinitelyTyped. @types tends to be used when the definition is not maintained by the package author, but it is nice to be a part of the package so you don't have to install another dependency.

**Comment by pixelshaded** [comment]
https://github.com/DefinitelyTyped/DefinitelyTyped/pull/28635

**Comment by jessepinho** [comment]
Bless you @pixelshaded ! Will integrate this into my own repo :)
