### ISSUE TITLE
Pass arguments to lifecycle hooks as per React API

### ISSUE THREAD

**Issue by JamieDixon** [JamieDixon/react-lifecycle-component#4]

**Comment by JamieDixon** [comment]
Fixed in https://github.com/JamieDixon/react-lifecycle-component/releases/tag/2.0.4

**Comment by jonaswindey** [comment]
I have a related issue, right now I've got everything working with the following code

```
export default connectWithLifecycle(
    ({application, kpis}) => ({application, kpis}),
    {...kpiActions, componentDidMount: kpiActions.fetchKpis}
)(Kpis)
```

However, I'd like to send an argument to the `fetchKpis`method, but with

```
export default connectWithLifecycle(
    ({application, kpis}) => ({application, kpis}),
    {...kpiActions, componentDidMount: kpiActions.fetchKpis('test')}
)(Kpis)
```

I get the error  `kpis.js?3b72:14 Uncaught (in promise) TypeError: dispatch is not a function`

**Comment by JamieDixon** [comment]
Hi @jonaswindey. Thanks for the heads up.

What's the result of `kpiActions.fetchKpis('test')` in this case? Are you able to produce a test repo demonstrating the issue you're having?

Cheers.
