### ISSUE TITLE
New Release?

### ISSUE THREAD

**Issue by aliu-d3d** [JamieDixon/react-lifecycle-component#6]
Hi, this library is really useful, but could you make a new npm release incorporating your latest changes?  npm is complaining about unmet peer dependencies, because the published version still lists "react-redux": "^4.0.0" as a peerDependency, and not the "^4.0.0 || ^5.0.0" you've got in master.

Thanks!

**Comment by JamieDixon** [comment]
Hi @aliu-d3d. Thanks for raising an issue. I'll look at getting a new release out ASAP now that https://github.com/JamieDixon/react-lifecycle-component/pull/7 has just landed.

**Comment by JamieDixon** [comment]
Version 2.0.5 has been published to npm: https://www.npmjs.com/package/react-lifecycle-component
